#!/bin/zsh
# Checks backlight before decreasing it in order not
# to turn the backlight completely off

BACKLIGHT=$(xbacklight -get)
SMALL_STEP=2
LARGE_STEP=5
STEP_THR=20

if [[ $1 == "up" ]]; then
	if [[ $BACKLIGHT -lt $STEP_THR ]]; then
		xbacklight -inc $SMALL_STEP
	else
		xbacklight -inc $LARGE_STEP
	fi
else
	if [[ $BACKLIGHT -gt $SMALL_STEP ]]; then
		if [[ $BACKLIGHT -lt $STEP_THR ]]; then
			xbacklight -dec $SMALL_STEP
		else
			xbacklight -dec $LARGE_STEP
		fi
	fi
fi
