#!/bin/bash

echo -n "$(xbacklight -get | cut -d"." -f1)%"

case $BLOCK_BUTTON in
	1) xbacklight -set 1 ;;
	3) xbacklight -set 100 ;;
	4) ~/.config/i3/i3blocks/backlight up ;;
	5) ~/.config/i3/i3blocks/backlight down ;;
esac
