#!/bin/bash

STEP=5

case $BLOCK_BUTTON in
	1) i3-msg exec pavucontrol > /dev/null ;;
	2) i3-msg exec pavucontrol > /dev/null ;;
	3) amixer -q sset Master toggle ;;
	4) amixer -q sset Master $STEP%+ ;;
	5) amixer -q sset Master $STEP%- ;;
esac

amixer get Master | sed -n "5p" | cut -d" " -f6 | sed -r 's/(\[|\])//g'
