#!/bin/bash

# Actually a line in the edited version of the volume widget
STEP=5

case $BLOCK_BUTTON in
	1) exec pavucontrol ;;
	2) exec pavucontrol ;;
	3) amixer -q sset Master toggle ;;
	4) amixer -q sset Master $STEP%+ ;;
	5) amixer -q sset Master $STEP%- ;;
esac

amixer get Master | sed -n "5p" | cut -d" " -f6 | sed -r 's/(\[|\])//g'
