#!/bin/bash

# A script that displays all the man pages currently available
# It keeps a list of the man pages, and updates it only when necessary
# This way rofi pops up much more quickly

DBFILE=~/.config/rofi/man.db

for dir in $(ls -d /usr/share/man/man*); do
	date=$(date -r /usr/share/man/$dir +%s)
	if [[ $date -gt $LASTEDIT ]]; then
		LASTEDIT=$date
	fi
done

if [[ ! -f $DBFILE || $LASTEDIT -gt $(date -r $DBFILE +%s) ]]; then
	perl -ne 'print length($_)." $_"' <<< $(apropos . | cut -d" " -f1-2) | sort -n | cut -d" " -f2- > $DBFILE
fi

if [[ -n $@ ]]; then
	NUM=$(sed -e 's/[\(\)]//g' <<< $(cut -d" " -f2 <<< $1))
	PAGE=$(cut -d" " -f1 <<< $1)

	herbstclient spawn urxvt -title "man $PAGE" -e "man $NUM $PAGE"
else
	cat $DBFILE
fi
