#!/bin/bash
cityfile=~/.config/rofi/cities.txt

if [[ -z $1 ]]; then
	cat $cityfile
	exit
fi

# Add city to the list if it's not present
grep -i -qs $1 $cityfile
if [[ $? -ne 0 ]]; then
	if [[ $1 != "" ]]; then
		echo $@ >> $cityfile
	fi
fi

herbstclient spawn urxvt -title "herbstweather" -e sh -c "/home/dbdexter/.config/rofi/weather_helper.sh $@"
killall rofi
