#!/usr/bin/env bash

cmds=()

hc() {
	cmds+=(";" "$@")
}

get_val() {
	xrdb -query | grep "hlwm.$1" | awk '{print $2}'
}


inactive_color=$(get_val "inactive_color")
border_color=$(get_val "border_color")
urgent_color=$(get_val "urgent_color")

statusbar_height=25
statusbar_border=3

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# hc keybind $Mod-a spawn ~/.config/herbstluftwm/layout_auto

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn urxvtd -q -o -f

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( "一" "二" "三" "四" "五" "六" ) #" 七 " " 八 " " 九 " " 十 ")
tag_keys=( {1..6} )

# Default frame split is horizontal
hc set default_frame_layout 1
# The default tag's layout has to be set separately, since default_frame_layout
# does not affect already existing tags
hc set_layout horizontal

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal vertical max grid				\
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-0 focus_monitor 0

# rofi
hc keybind $Mod-d spawn rofi -show run -modi "run,man:~/.config/rofi/man,window"
# hc keybind XF86Search spawn rofi -show youtube -modi "youtube:~/.config/rofi/youtube,google:~/.config/rofi/web"
hc keybind $Mod-w spawn rofi -show weather -modi "weather:~/.config/rofi/weather"

# screenshot
hc keybind Print spawn scrot ~/Screenshots/%Y-%m-%d-%H:%M:%S_sshot.png
hc keybind $Mod-Shift-x spawn ~/.config/herbstluftwm/lock.sh

# multimedia keys
hc keybind XF86AudioMute spawn amixer set Master toggle						# Toggle mute-unmute
hc keybind XF86AudioLowerVolume spawn amixer set Master 5%-					# Lower volume
hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+					# Increase volume
hc keybind XF86MonBrightnessUp spawn ~/.config/herbstluftwm/backlight up		# Increase screen brightness
hc keybind XF86MonBrightnessDown spawn ~/.config/herbstluftwm/backlight down	# Decrease screen brightness

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $border_color
hc set frame_border_normal_color $inactive_color
hc set frame_bg_normal_color $inactive_color
hc set frame_bg_active_color $border_color
hc set frame_border_width 2
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 10
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color $border_color
hc attr theme.normal.color $inactive_color
hc attr theme.urgent.color $urgent_color
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $inactive_color
hc attr theme.active.outer_color $inactive_color
hc attr theme.background_color black

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients

# status bar padding
hc pad 0 $(($statusbar_height + $statusbar_border)) 0 0 0

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on focus=on
hc rule class='Pinentry' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient chain "${cmds[@]}" &

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#+++++++++++ Custom window layouts ++++++++++++
# Somewhat productive layout on first workspace
# herbstclient load ${tag_names[0]} "(split horizontal:0.6:0 (clients vertical:0) (split vertical: 0.4:1 (clients horizontal:0) (clients horizontal:0)))"
# Firefox: workspace 3
herbstclient rule class=Firefox tag="${tag_names[2]}"

#++++++++++ Reload all accessory functions ++++++++++
herbstclient spawn killall polybar
herbstclient spawn polybar hlwm
